=== javsanpae/1ASIR_LMSGI/XML/u5/ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="CatalogoPeliculas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Pelicula" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType> 
    </xs:element>

    <xs:element name="Pelicula">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Titulo" type="xs:string" />
                <xs:element name="Duracion" type="xs:string" />
                <xs:element name="Genero" type="xs:string" />
                <xs:element ref="Actores" />
                <xs:element name="Fecha" type="xs:integer" />
                <xs:element name="Director" type="xs:string" />
                <xs:element name="Formato" type="xs:string" default="AVI" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Actores">
        <xs:complexType>
            <xs:choice maxOccurs="3">
                <xs:element name="Actor" type="xs:string" />
                <xs:element name="Actriz" type="xs:string" />
            </xs:choice>
        </xs:complexType>
    </xs:element>









</xs:schema>

=== javsanpae/1ASIR_LMSGI/XML/u5/ejercicio2.xml
<?xml version="1.0"?>
<CatalogoPeliculas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="ejercicio2.xsd">

    <Pelicula>
        <Titulo>The Matrix</Titulo>
        <Duracion>136</Duracion>
        <Genero>Sci-Fi and Fantasy</Genero>
        <Actores>
            <Actor>Keanu Reeves</Actor>
            <Actor>Laurence Fishburne</Actor>
            <Actriz>Carrie Ann Moss</Actriz>
        </Actores>
        <Fecha>1999</Fecha>
        <Director>Wachowski Brothers</Director>
        <Formato>MP4</Formato>
    </Pelicula>

    <Pelicula>
        <Titulo>Titanic</Titulo>
        <Duracion>194</Duracion>
        <Genero>Drama</Genero>
        <Actores>
            <Actor>Leonardo DiCaprio</Actor>
            <Actriz>Kate Winslet</Actriz>
        </Actores>
        <Fecha>1999</Fecha>
        <Director>James Cameron</Director>
        <Formato>AVI</Formato>
    </Pelicula>

    <Pelicula>
        <Titulo>The Sixth Sense</Titulo>
        <Duracion>106</Duracion>
        <Genero>Thriller</Genero>
        <Actores>
            <Actor>Bruce Willis</Actor>
            <Actor>Haley Joel Osment</Actor>
        </Actores>
        <Fecha>1999</Fecha>
        <Director>M. Night Shyamalan</Director>
        <Formato>MP4</Formato>
    </Pelicula>

</CatalogoPeliculas>
