=== javsanpae/1ASIR_LMSGI/XML/u5/exercise5_v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element ref="contenido" />
                <xs:element name="copyright" type="xs:positiveInteger" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="contenido">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="capitulo" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="capitulo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tema" type="xs:string" />
                <xs:element ref="seccion" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="materia" type="xs:string" use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:element name="seccion">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="apartados" type="xs:int" use="required"/>
                    <xs:attribute name="dificil" type="xs:string" use="optional" default="si"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== javsanpae/1ASIR_LMSGI/XML/u5/exercise5.xml
<?xml version="1.0" encoding="UTF-8"?>
<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./exercise5_v1.xsd">

    <titulo>Java y XML</titulo>


    <contenido>

        <capitulo materia="XML">
            <tema>Introduccion</tema>
            <seccion apartados="7">Que es</seccion>
            <seccion apartados="3">Como se usa</seccion>
        </capitulo>

        <capitulo materia="XML">
            <tema>Creando XML</tema>
            <seccion apartados="0">Un documento XML</seccion>
            <seccion apartados="2">La cabecera</seccion>
            <seccion apartados="6">El contenido</seccion>
        </capitulo>

        <capitulo>
            <tema>Analizando XML</tema>
            <seccion apartados="3">Preparacion</seccion>
            <seccion apartados="3" dificil="si">SAX</seccion>
            <seccion apartados="9" dificil="si">Manejadores</seccion>
            <seccion apartados="0">Una forma mejor de cargar el analizador</seccion>
        </capitulo>

        <capitulo materia="Java">
            <tema>JDOM</tema>
            <seccion apartados="2">Introduccion</seccion>
            <seccion apartados="4" dificil="si">DOM&amp;JDOM</seccion>
        </capitulo>

    </contenido>

    <copyright>2000</copyright>

</libro>

<!-- Este documento es el enunciado dado en el temario -->
