=== javsanpae/1ASIR_LMSGI/XML/examenSchemas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="dams">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="source" type="xs:anyURI" />
                <xs:element ref="dam" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="province" type="xs:string" use="required" />
        </xs:complexType>        
    </xs:element>

    <xs:element name="dam">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="administrative_data" />
                <xs:element ref="geographical_data" />
                <xs:element ref="dam_features"/>
                <xs:element name="image" type="xs:anyURI" />
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="administrative_data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="owner" type="xs:string" />
                <xs:element name="potential_risk_category" type="xs:string" default="A" />
                <xs:element name="construction_end" type="xs:date" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="geographical_data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="river" type="xs:string" />
                <xs:element name="town" type="xs:string" />
                <xs:element name="hydrographic_basin" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="dam_features">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="type" type="xs:string" />
                <xs:element name="crest_elevation" type="length_int" />
                <xs:element name="crest_length" type="length_int" />
                
                <xs:element name="height_from_foundations" type="length_float" />
                <xs:element name="foundations_peak" type="length_float" />
                <xs:element name="bed_level" type="length_float" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

        <xs:complexType name="length_int">
            <xs:sequence>
                <xs:element name="value" type="xs:int" />
                <xs:element name="unit" type="xs:string" fixed="m" />
            </xs:sequence>
        </xs:complexType>


        <xs:complexType name="length_float">
            <xs:sequence>
                <xs:element name="value" type="xs:float" />
                <xs:element name="unit" type="xs:string" fixed="m" />
            </xs:sequence>
        </xs:complexType>


</xs:schema>

=== javsanpae/1ASIR_LMSGI/XML/examen/examenSchemas.xml
<?xml version="1.0" encoding="UTF-8"?>
<dams xmlns:xs="http://www.w3.org/2001/XMLSchema-Instance" xs:noNamespaceSchemaLocation="examenSchemas.xsd" province="Granada">

    <source>http://sig.mapama.es/snczi/visor.html</source>

    <dam name="Laguna de las Yeguas">
        <administrative_data>
            <owner>State</owner>
            <potential_risk_category>C</potential_risk_category>
            <construction_end>1977-01-01</construction_end>
        </administrative_data>

        <geographical_data>
            <river>Dílar</river>
            <town>Dílar</town>
            <hydrographic_basin>Guadalquivir</hydrographic_basin>
        </geographical_data>

        <dam_features>

            <type>Loose materials</type>

            <crest_elevation>
                <value>2900</value>
                <unit>m</unit>
            </crest_elevation>

            <height_from_foundations>
                <value>21.4</value>
                <unit>m</unit>
            </height_from_foundations>

            <crest_length>
                <value>211</value>
                <unit>m</unit>
            </crest_length>

            <foundations_peak>
                <value>2878.6</value>
                <unit>m</unit>
            </foundations_peak>
            
            <bed_level>
                <value>2882.8</value>
                <unit>m</unit>
            </bed_level>

        </dam_features>

        <image>lagunayeguas.jpg</image>
    </dam>

    <dam name="Béznar">
        <administrative_data>
            <owner>Junta de Andalucía</owner>
            <potential_risk_category>A</potential_risk_category>
            <construction_end>1986-12-31</construction_end>
        </administrative_data>

        <geographical_data>
            <river>Ízbor</river>
            <town>El Pinar</town>
            <hydrographic_basin>Cuenca Mediterránea Andaluza</hydrographic_basin>
        </geographical_data>

        <dam_features>

            <type>Arch</type>

            <crest_elevation>
                <value>489</value>
                <unit>m</unit>
            </crest_elevation>

            <height_from_foundations>
                <value>134.0</value>
                <unit>m</unit>
            </height_from_foundations>

            <crest_length>
                <value>408</value>
                <unit>m</unit>
            </crest_length>

            <foundations_peak>
                <value>354.8</value>
                <unit>m</unit>
            </foundations_peak>
            
            <bed_level>
                <value>379.8</value>
                <unit>m</unit>
            </bed_level>

        </dam_features>

        <image>beznar.jpg</image>
    </dam>

    <dam name="Los Bermejales">
        <administrative_data>
            <owner>State</owner>
            <potential_risk_category>A</potential_risk_category>
            <construction_end>1958-01-01</construction_end>
        </administrative_data>

        <geographical_data>
            <river>Cacín</river>
            <town>Arenas del Rey</town>
            <hydrographic_basin>Guadalquivir</hydrographic_basin>
        </geographical_data>

        <dam_features>

            <type>Gravity</type>

            <crest_elevation>
                <value>831</value>
                <unit>m</unit>
            </crest_elevation>

            <height_from_foundations>
                <value>67.19</value>
                <unit>m</unit>
            </height_from_foundations>

            <crest_length>
                <value>408</value>
                <unit>m</unit>
            </crest_length>

            <foundations_peak>
                <value>769.0</value>
                <unit>m</unit>
            </foundations_peak>
            
            <bed_level>
                <value>775.35</value>
                <unit>m</unit>
            </bed_level>

        </dam_features>

        <image>bermejales.jpg</image>
    </dam>

</dams>
