=== javsanpae/1ASIR_LMSGI/XML/u5/xschema_project/SanchezJavier_XSchemaProject.xsd
<?xml version="1.0" encoding="UTF-8"?>

    <!-- 
    TITLE OF THE PROJECT: XML+Schema Project
    NAMES OF THE AUTHORS: Javier Sánchez Páez
    YEAR AND GROUP: 1st ASIR-A bil
    DATE OF SUBMISSION: dd/mm/2022  
    -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="games_library">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="game" maxOccurs="unbounded" /> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="game">
        <xs:complexType>
            <xs:all>
                <!-- all of these elements are required but in the order we want -->
                <xs:element ref="listed" />
                <xs:element ref="name" />
                <xs:element ref="game_shop" />
                <xs:element ref="release_year" />
                <!-- We'll do a reusable type here to have better and cleaner code -->
                <xs:element name="developer_info" type="CT_info" />
                <xs:element name="publisher_info" type="CT_info" />
                <xs:element ref="user_reviews" />
                <xs:element ref="tags" />
                <xs:element name="trailer" type="xs:anyURI" />
                <xs:element ref="compatibility" />
                <xs:element ref="prices" />
                <xs:element ref="dlc" />
                <xs:element ref="languages" />
                <xs:element ref="game_info" />
            </xs:all>
            <xs:attribute name="category" use="required" type="gameCategories" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="gameCategories">
        <xs:restriction base="xs:string">
            <!-- Here we have some categories/genres of games. We can add as much as we want -->
            <xs:enumeration value="Racing" />
            <xs:enumeration value="RPG" />
            <xs:enumeration value="Adventure" />
            <xs:enumeration value="Science/Fiction" />
            <xs:enumeration value="Emulation" />
            <xs:enumeration value="Roleplay" />
            <xs:enumeration value="Simulation" />
            <xs:enumeration value="Survival" />
            <xs:enumeration value="Horror" />
            <xs:enumeration value="Learning" />
            <xs:enumeration value="Shooter" />
            <xs:enumeration value="MMORPG" />
            <xs:enumeration value="Combat" />
            <xs:enumeration value="Casual" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="listed">
        <xs:complexType />
    </xs:element>

    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!-- The name of the game must have at least 3 letter and a maximum of 50 letters -->
                <xs:minLength value="3" />
                <xs:maxLength value="50" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="game_shop">
        <xs:simpleType>
            <!-- Here we have some of the most known games platforms -->
            <xs:restriction base="xs:string">
                <xs:enumeration value="Steam" />
                <xs:enumeration value="Origin" />
                <xs:enumeration value="Battle.Net" />
                <xs:enumeration value="GOG" />
                <xs:enumeration value="Rockstar Games" />
                <xs:enumeration value="Epic Games" />
                <!-- In case we have an indie/independent game, we have this option available -->
                <xs:enumeration value="Independent" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="release_year">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:gYear">
                    <!-- This attribute is optional because if the game is from the 2000 for example we already know it's been released. We add the true by default because the majority of games on these webpages are already released -->
                    <xs:attribute name="released" type="xs:boolean" use="optional" default="true" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <!-- We'll use the same elements on developer and publisher info -->
    <xs:complexType name="CT_info">
        <xs:sequence>
            <!-- Name and website are unbounded because a game can have several developers and/or publishers as we can see on the second game --> 
            <xs:element name="name" type="xs:string" maxOccurs="unbounded" />
            <xs:element name="website" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!-- An opinion on these platforms are composed of the posible review and the total of reviews -->
    <xs:simpleType name="unionReviews">
        <xs:union memberTypes="T_optionReviews T_totalReviews" />
    </xs:simpleType>

    <xs:simpleType name="T_optionReviews">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Not_Available" />
            <xs:enumeration value="Very_Negative" />
            <xs:enumeration value="Negative" />
            <xs:enumeration value="Mixed" />
            <xs:enumeration value="Positive" />
            <xs:enumeration value="Very_Positive" />
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="T_totalReviews">
        <xs:restriction base="xs:nonNegativeInteger">
            <!-- In case we have 0 reviews we'll use the "Not_Available" option on T_optionReviews -->
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="999999" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="listReviews">
        <xs:list itemType="unionReviews" />
    </xs:simpleType>

    <xs:element name="user_reviews">
        <xs:simpleType>
            <xs:restriction base="listReviews">
                <!-- We can have max. 2 arguments here, which will be the optionReview and the totalReview. -->
                <xs:length value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- We can have as much tags as we want -->
    <xs:element name="tags">
        <xs:simpleType>
            <xs:list itemType="xs:string" />
        </xs:simpleType>
    </xs:element>

    <!-- Some of the most common gaming platforms -->
    <xs:simpleType name="compatibilityList">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Windows" />
            <xs:enumeration value="Mac_OS_X" />
            <xs:enumeration value="Linux" />
            <xs:enumeration value="Steam_OS" />
        </xs:restriction>
    </xs:simpleType>

    <!-- Here we are doing a list of platforms in case there is more than 1 compatible platform -->
    <xs:element name="compatibility">
        <xs:simpleType>
            <xs:list itemType="compatibilityList" />
        </xs:simpleType>
    </xs:element>

    <xs:simpleType name="listPrices">
        <xs:list itemType="xs:double" />
    </xs:simpleType>

    <xs:element name="prices">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="listPrices">
                    <xs:attribute name="has_discount" type="xs:boolean" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="dlc">
        <xs:complexType>
            <xs:attribute name="available" type="xs:boolean" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="languagesAvailable">
        <xs:restriction base="xs:string">
            <!-- Here I listed some of the most spoken languages on the world --> 
            <xs:enumeration value="Spanish" />
            <xs:enumeration value="English" />
            <xs:enumeration value="French" />
            <xs:enumeration value="Italian" />
            <xs:enumeration value="German" />
            <xs:enumeration value="Japanese" />
            <xs:enumeration value="Mandarin" />
            <xs:enumeration value="Hindi" />
            <xs:enumeration value="Russian" />
            <xs:enumeration value="Arabic" />
            <xs:enumeration value="Portuguese" />
            <xs:enumeration value="Bengali" />
            <xs:enumeration value="Indonesian" />
            <xs:enumeration value="Simplified_Chinese" />
            <xs:enumeration value="Traditional_Chinese" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="languagesList">
        <xs:list itemType="languagesAvailable" />
    </xs:simpleType>

    <xs:element name="languages">
        <xs:simpleType>
            <xs:restriction base="languagesList" />
        </xs:simpleType>
    </xs:element>

    <xs:element name="game_info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string" />
                <xs:element name="about" type="xs:string" />
                <xs:element ref="changelog" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Changelogs are used as a way of communication between the developer and the community to inform about new updates, solved errors and new content available --> 
    <xs:element name="changelog">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="last_changelog" />
                <xs:element name="changelog_title" type="xs:string" />
                <xs:element name="changelog_description" type="xs:string" />
                <xs:element name="changelog_link" type="xs:anyURI"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="last_changelog">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <!-- Pattern of the dd/mm/yyyy format -->
                <xs:pattern value="\d{2}/\d{2}/\d{4}" />
                <xs:length value="10"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== javsanpae/1ASIR_LMSGI/XML/u5/xschema_project/Games/SanchezJavier_XSchemaProject.xml
<?xml version="1.0" encoding="UTF-8"?>

    <!-- 
    TITLE OF THE PROJECT: XML+Schema Project
    NAMES OF THE AUTHORS: Javier Sánchez Páez
    YEAR AND GROUP: 1st ASIR-A bil
    DATE OF SUBMISSION: dd/mm/2022  
    -->

<games_library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./SanchezJavier_XSchemaProject.xsd">

    <game category="Racing">

        <listed />

        <name>Assetto Corsa</name>

        <game_shop>Steam</game_shop>
        
        <release_year released="true">2014</release_year>

        <developer_info>
            <name>Kumos Simulazioni</name>
            <website>http://www.kunos-simulazioni.com/main/</website>
        </developer_info>

        <publisher_info>
            <name>Kumos Simulazioni</name>
            <website>http://www.kunos-simulazioni.com/main/</website>
        </publisher_info>

        <user_reviews>Very_Positive 1061</user_reviews>

        <tags>Racing Cars Multiplayer Simulation Driving</tags>

        <trailer>https://www.youtube.com/watch?v=Hndf5pyVVzc</trailer>

        <compatibility>Windows Linux Steam_OS</compatibility>

        <prices has_discount="true">3.99 2.13 7.93</prices>
        <dlc available="true"/>
        <languages>English Spanish Simplified_Chinese Traditional_Chinese</languages>

        <game_info>
            <description>Assetto Corsa v1.16 introduces the new "Laguna Seca" laser-scanned track, 7 new cars among which the eagerly awaited Alfa Romeo Giulia Quadrifoglio! Check the changelog for further info!</description>

            <about>
                NEXT GENERATION RACING SIMULATOR
                Assetto Corsa features an advanced DirectX 11 graphics engine that recreates an immersive environment, dynamic lighthing and realistic materials and surfaces. The advanced physics engine is being designed to provide a very realistic driving experience, including features and aspects of real cars, never seen on any other racing simulator such as tyre flat spots, heat cycles including graining and blistering, very advanced aerodynamic simulation with active movable aerodynamics parts controlled in real time by telemetry input channels, hybrid systems with kers and energy recovery simulation. Extremely detailed with single player and multiplayer options, exclusive licensed cars reproduced with the best accuracy possible, thanks to the official cooperation of Car Manufacturers.
                ASSETTO CORSA has been developed at the KUNOS Simulazioni office, located just inside the international racing circuit of Vallelunga, allowing the team to develop the game with the cooperation of real world racing drivers and racing teams.
            </about>

            <changelog>
                
                <last_changelog>16/02/2018</last_changelog>

                <changelog_title>
                    505 GAMES AND KUNOS ANNOUNCE THE RELEASE OF ASSETTO CORSA ULTIMATE EDITION
                </changelog_title>
                
                <changelog_description>
                    Kunos Simulazioni and 505 Games are proud to announce the Assetto Corsa Ultimate Edition; the most complete package ever conceived for the critically acclaimed and ground breaking racing simulator.

                    Using laser scanning technology to deliver the highest level of accuracy possible, Assetto  Corsa Ultimate Edition boasts 33 track configurations from sixteen circuits, alongside an advanced physics engine built using practical knowledge acquired from the elite of motorsport, including features and aspects of real cars never seen on any other racing simulator, such as tyre flat spots, heat cycles, including graining and blistering.

                    Check out now the Assetto Corsa website for updates: something big is going to happen!
                </changelog_description>

                <changelog_link>https://www.assettocorsa.it/505-games-and-kunos-announce-the-release-of-assetto-corsa-ultimate-edition/</changelog_link>

            </changelog>
        </game_info>
    </game>

    <game category="RPG">

        <listed />

        <name>Elden Ring</name>

        <game_shop>Steam</game_shop>

        <release_year released="true">2022</release_year>
        
        <developer_info>
            <name>FromSoftware Inc</name>
            <website>https://www.fromsoftware.jp/ww/</website>
        </developer_info>

        <publisher_info>
            <name>FromSoftware Inc</name>
            <name>BANDAI NAMCO ENTERTAINMENT</name>
            <website>https://www.fromsoftware.jp/ww/</website>
            <website>https://en.bandainamcoent.eu/</website>
        </publisher_info>

        <user_reviews>Very_Positive 111134</user_reviews>

        <tags>Souls-like Dark_Fantasy PvP</tags>

        <trailer>https://www.youtube.com/watch?v=OT8if6DXOFQ</trailer>

        <compatibility>Windows</compatibility>

        <prices has_discount="false">59.99 79.99</prices>

        <dlc available="false" />

        <languages>English French Italian German Spanish</languages>

        <game_info>
            <description>THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between</description>

            <about>
                A vast world where open fields with a variety of situations and huge dungeons with complex and three-dimensional designs are seamlessly connected. As you explore, the joy of discovering unknown and overwhelming threats await you, leading to a high sense of accomplishment.
            </about>

            <changelog>

                <last_changelog>04/04/2022</last_changelog>

                <changelog_title>Patch Notes Version 1.03.3</changelog_title>

                <changelog_description>We are distributing this new update to fix a bug in patch 1.03.</changelog_description>

                <changelog_link>https://store.steampowered.com/news/app/1245620/view/3184615391704558008</changelog_link>

            </changelog>
        </game_info>
    </game>

    <game category="Shooter">

        <listed />

        <name>Call Of Duty: Warzone</name>

        <game_shop>Battle.Net</game_shop>

        <release_year released="true">2020</release_year>
        
        <developer_info>
            <name>Infinity Ward</name>
            <name>Raven Software</name>
            <website>https://www.infinityward.com</website>
            <website>https://www.ravensoftware.com/</website>
        </developer_info>

        <publisher_info>
            <name>Activision</name>
            <website>https://www.activision.com/</website>
        </publisher_info>

        <user_reviews>Very_Positive 248221</user_reviews>

        <tags>Shooter PvP Battle_Royale Rebirth</tags>

        <trailer>https://www.youtube.com/watch?v=OT8if6DXOFQ</trailer>

        <compatibility>Windows Mac_OS_X</compatibility>

        <prices has_discount="false">0</prices>

        <dlc available="true" />

        <languages>English Hindi Traditional_Chinese Italian German Spanish</languages>

        <game_info>
            <description>Trouble is brewing deep beneath Caldera. Butcher has discovered once-secret laboratories where Nebula V bombs have been in production with the intent of wiping various metropolises off the map. Season Two of Call of Duty®: Warzone™ unlocks the Search and Deploy Event, where players are tasked with taking out Armored Transport trucks while infiltrating Chemical Research Laboratories before taking siege of the Chemical Factory. Take advantage of the Redeploy Balloon around Caldera to redeploy from hot engagements or from fast circling gas. And take to the air by piloting Bombers that can turn the tides of war in an instant. Season Two also brings new game features to Warzone™. Strap on your gas mask and drop in.
            </description>

            <about>
                Buy the Season Two Battle Pass and get back up to 1300 CP as you level up. Use them to buy the next season’s Battle Pass so the action never stops.
            </about>

            <changelog>

                <last_changelog>26/01/2022</last_changelog>

                <changelog_title>BUG FIXES</changelog_title>

                <changelog_description>Fixed collision issues with various elements across Caldera allowing Players to exploit/peek/shoot through them.</changelog_description>

                <changelog_link>https://www.ravensoftware.com/community/2021/12/call-of-duty-vg-warzone-season-one-patch-notes</changelog_link>

            </changelog>
        </game_info>
    </game>


</games_library>
